required:
  type:
    const: "living/zettelkasten"
  key:
    type: string
    pattern: "^(?=.{1,64}$)(?=.*[a-z])[a-z0-9]+(?:-[a-z0-9]+)*$"
  tags:
    type: array
    contains: "topic-tag"
optional:
  sources:
    type: array
  related:
    type: array
  follows:
    type: string
  sequence:
    type: integer
