"""Owner behaviour for typed managed session bootstrap."""

from __future__ import annotations

import pytest

from _application.registry import current_application_catalogue, current_request_resolver
from _application.session.start import SessionStartRequest
from _application.types import DependencyTier, EffectClass
from command_application import application_for


def test_session_start_returns_typed_bootstrap_and_refreshes_mirror(
    command_vault_clone,
):
    application = application_for(
        command_vault_clone.vault_root,
        dependency_tier=DependencyTier.MANAGED,
    )

    result = application.invoke(SessionStartRequest())

    assert result.status == "ok"
    assert result.result.brain_core_version == "0.54.27"
    assert result.result.active_profile == "reader"
    assert result.result.core_bootstrap
    assert result.result.core_docs
    assert result.result.artefacts
    assert result.result.config.default_profile == "operator"
    assert not hasattr(result.result, "context")
    mirror = command_vault_clone.vault_root / ".brain/local/session.md"
    assert mirror.is_file()
    rendered = mirror.read_text(encoding="utf-8")
    assert rendered.startswith("<!-- Generated by .brain-core/scripts/session.py.")
    assert "# Brain Session" in rendered


def test_session_start_carries_trusted_workspace_context(command_vault_clone):
    workspace = command_vault_clone.vault_root.parent / "agent-workspace"
    workspace.mkdir()
    application = application_for(
        command_vault_clone.vault_root,
        dependency_tier=DependencyTier.MANAGED,
        workspace_dir=workspace.resolve(),
    )

    result = application.invoke(SessionStartRequest())

    assert result.result.workspace.directory == str(workspace.resolve())
    assert result.result.workspace.location == "external"
    assert result.result.workspace_configuration.binding_status == "not configured"


def test_session_start_catalogue_declares_managed_cache_effect():
    entry = next(
        item
        for item in current_application_catalogue().entries
        if item.command_id == "session.start"
    )

    assert entry.dependency_tier is DependencyTier.MANAGED
    assert entry.effect_class is EffectClass.DERIVED_CACHE_WRITE
    assert entry.optional_providers == ("obsidian_cli",)


def test_session_start_transport_rejects_legacy_noop_context():
    resolver = current_request_resolver()

    assert type(resolver.resolve("session.start", {})) is SessionStartRequest
    with pytest.raises(ValueError, match="unexpected fields"):
        resolver.resolve("session.start", {"context": "ignored"})
